### ISSUE TITLE
Cannot deploy successfully

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#1]
https://travis-ci.com/botorange/wechaty-puppet-padplus/jobs/232203206

Always says
```
2.27s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Fetching: dpl-1.10.12.gem (100%)
Successfully installed dpl-1.10.12
1 gem installed
invalid option "--api_key="
failed to deploy
```

I had tried https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow to export token, and tried this: https://docs.travis-ci.com/user/deployment/npm/

I found `echo $NPM_TOKEN` print no result... So I guess maybe I failed export $NPM_TOKEN  ....

```diff
    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."
        - npm version
        - ./scripts/generate-version.sh
        - ./scripts/package-publish-config-tag.sh
        - npm run dist
        - echo "NPM Building Finished."
+        - echo $NPM_TOKEN
```

**Comment by huan** [comment]
https://github.com/botorange/wechaty-puppet-padplus/blob/6d61f6d336383fe775bd59ee9eb4aae51e358e34/.travis.yml#L44-L49

It seems that your NPM_TOKEN is invalid in your Travis CI settings.

BTW: It's very dangerous to export your NPM_TOKEN to the public. `echo $NPM_TOKEN` will get nothing because Travis CI is trying to protect you.

**Comment by windmemory** [comment]
@huan Thanks for pointing this out. We will put the `NPM_TOKEN` into the travis env var.

**Comment by lijiarui** [comment]
fix. thanks!
